security-properties:
  cors:
    origins:
      - "https://test-url.co.kr"
      - "http://localhost:3000"
    methods:
        - GET
        - POST
        - PUT
        - DELETE
  no-auth-urls:
    - "/login"
    - "/register"
  jwt:
    access:
      private-key: iPJU5kHFwHlk9SoGKkoujvgRVL7AOIIJZAA1+QcGRLU= # openssl rand -base64 32
      public-key:
      expiring-time: 30m
      algorithm: HS256
    refresh:
      private-key: |
        -----BEGIN PRIVATE KEY-----
        IWMP4aHYIPGjizExPWtXgQtFfqw57/NosFx38Zw5/8o=
        -----END PRIVATE KEY-----
      public-key: |
        -----BEGIN PUBLIC KEY-----
        YOUR_PUBLIC_KEY_HERE
        -----END PUBLIC KEY-----
      expiring-time: 7d
      algorithm: RS512
