security-properties:
#  prod-profile: "prod"
  cors:
    origins:
      - "https://test-url.co.kr"
      - "http://localhost:3000"
    methods:
        - GET
        - POST
        - PUT
        - DELETE
  no-auth-urls:
    - "/login"
    - "/register"
    - "/refresh"
  jwt:
    access:
      private-key: iPJU5kHFwHlk9SoGKkoujvgRVL7AOIIJZAA1+QcGRLU= # openssl rand -base64 32
      public-key:
      expiring-time: 30m
      algorithm: HS256
    refresh:
      private-key: | # openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
        -----BEGIN PRIVATE KEY-----
        MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC/KBZT69BnYwPj
        AJU3K5I0kYAOMdIU++dKLYin6UW0TOtbkfX/VnF2OdKqSiVKVtW8LbteS9hgeO7X
        axn6G9KDXWeKW69OqVm3W+0x/plxf4g+XevHtWU81io5veb2zqOAHVA84opnCFvz
        hrbIdaSZhIjgumNusQxBIJmLx2WLiVNwF1t6GFHRyR+lYMGsd8b0oorhW09G3j2R
        hlPZ7wlX89QkMZ0jNjHLEGCu85OKitA+/MQWe8TpkXkUdKO9KVr9a0TUNqfSFYXO
        bbMI17k1rlYXUiAHE/WMkBMjGJubzwHXVCoQ1P/eXevfyxdh50g2+IbQwa987iy3
        K6PnlLd/AgMBAAECggEANvjxStsTCNhpwrtlLgOCvUlmmS5sqwoyXpuvpBIqsIo6
        WRAlvXN/l69TTRObm8BTIRXJv3lyVXQRw7OSOeIMbSjMYPay+J0tJtTx5qHAQOqb
        JMxfxQP+hDtW01owdKPCU1Kaw5emk7DMuMDyCb4DQv7hWjdf5vJVgtk8Lv19z12E
        fAvGJjfTAzBrfUFDrTCy/w5jYOp0Jh/rxYaJiMr1QWlwmOapup4gDMZb25YvXfIw
        Ec57/0+jHSXPyH0O/SSobnSlQ55S/YoVzYl6djlPaCLvDsexaFajv19SSYijZ9wh
        ZqC/zoVS5wgSJXI3Z0hRDBivGUbBlLsQTfDbDmnDCQKBgQDdjkRIiPhmzEPx58tZ
        jyQN7TdvNGmx6EoysNM+N77XhIuua4X7Y234Ql+dzSVm7lBYitu8WkarkgEHuj8d
        /aUHxIvfTmNBbjlG5dsSs4e8y/FVSdAwIU1tjQiovJOTlKLlN7d/0S92ho7degZp
        gwkDgOVDp/4Bu3CRdnoW6ZBrmwKBgQDc3/XKJn4ubyLh5aurlsuXPNXZ+9YmHan0
        ENH1Pz4W5i7JM9aPMNz0/sMyzqcVNHI9S+mIULPSvX4XzwoF41OfOz+mZFJrpgk2
        8Lt78sG/ySeZspbdtZv86E0Nx47dxyXmm188jFI9SV7RJPxYOPtpxhfkOk1U2RpT
        zkSFAHNb7QKBgGuitTvEB2HxtMSuRtWQvARkDX1iKkM7RejQjR/59yY/B5lKNYJG
        8OMeY9OHGbei6bfKZixgc1rhCM0XR5irZGScsRNgwsnD4eG2w7KXM8eeEPXNcW4g
        j7w8O0u2qb+WA3l2kxhuqS9c+cVRhhH2jgd8tGUlFTsENBEHTRMaj4YnAoGBAMzn
        P9/fQePV2ihypoWyiQCuwT1OMeZ+UnJHQGAh4Xng5LpnSr7f97uYtIFn0P0NAIX4
        7Jc3NvtkK5vuyD+aGrN3hZ7ZJtUS3S2IuoVMOY2wEPq3ANqBZkqDPyhvXwxDeder
        f/htvMV6UWn4w9kcU7BWw0dJBwCVv6TLkClKt7opAoGBAKuTwnu/+bXhcq3In3Ix
        D9J5qGbkehxs41weUSslpzVNHRnmIzsoQ4EhycciOsUlf5+BzpvkEhNWkX3sldEI
        qgWmj1NcR0nmfXxt7i2qtpFrO/9fl3VJGjNRlyFXt9Sj/vUhmMAuC/wdYafWuSFy
        LQgVPukmGv2/4Y7Vl2YUChwS
        -----END PRIVATE KEY-----
      public-key: | # openssl rsa -in private_key.pem -pubout -out public_key.pem
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvygWU+vQZ2MD4wCVNyuS
        NJGADjHSFPvnSi2Ip+lFtEzrW5H1/1ZxdjnSqkolSlbVvC27XkvYYHju12sZ+hvS
        g11niluvTqlZt1vtMf6ZcX+IPl3rx7VlPNYqOb3m9s6jgB1QPOKKZwhb84a2yHWk
        mYSI4LpjbrEMQSCZi8dli4lTcBdbehhR0ckfpWDBrHfG9KKK4VtPRt49kYZT2e8J
        V/PUJDGdIzYxyxBgrvOTiorQPvzEFnvE6ZF5FHSjvSla/WtE1Dan0hWFzm2zCNe5
        Na5WF1IgBxP1jJATIxibm88B11QqENT/3l3r38sXYedINviG0MGvfO4styuj55S3
        fwIDAQAB
        -----END PUBLIC KEY-----
      expiring-time: 7d
      algorithm: RS512
